# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91b244743508e6bd22f34d5717061055ca440c74977ebccc3fb6fdee328357d03312c8a090e2ccd706b804a01161ccee3bdd45ffa2566121ada64d43980a3e68

test:
  secret_key_base: 7b35d3a103e73a463fabedbf090b61302ba1e7bace675634fe08c8eeda0165b6e8058ab29c11767eb18afe3bef9012df3f3e3e28e67b5a6a85f409a88534d0bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
